/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x77, 0xC7, 0xDB, 0x11, 0x29, 0xFB, 0xFE, 0xA5}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 1
#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 8
#define VIAL_COMBO_ENTRIES 2
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

